export const NODE_ENV = process.env.NODE_ENV;
export const REACT_APP_FIREBASE_EMULATORS =
  process.env.REACT_APP_FIREBASE_EMULATORS;

export const REACT_APP_FIREBASE_PROJECT_ID =
  process.env.REACT_APP_FIREBASE_PROJECT_ID;
export const REACT_APP_FIREBASE_PROJECT_WEB_API_KEY =
  process.env.REACT_APP_FIREBASE_PROJECT_WEB_API_KEY;
