blank_issues_enabled: false
contact_links:
  - name: 🤔 Need support / Q&A
    url: https://github.com/rowyio/rowy/discussions/categories/support-q-a
    about: Raise a support query on Github Discussion
  - name: 🙌 Want to join our team?
    url: https://www.rowy.io/jobs
    about: Get in touch to contribute & work with Rowy
